stages:
#  - build
  - deploy

#build:
#  image: docker:cli
#  stage: build
#  variables:
#    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
#  # before_script:
#    # - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#  # All branches are tagged with $DOCKER_IMAGE_NAME (defaults to commit ref slug)
#  # Default branch is also tagged with `latest`
#  script:
#    - ls
#    - docker context create builder
#    - docker buildx create builder --use
#    - docker buildx build --target release --platform linux/arm64,linux/amd64 -t chaos2theory/personal-site:latest .
#    # - docker push "$DOCKER_IMAGE_NAME"
#    # - |
#    #   if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
#    #     docker tag "$DOCKER_IMAGE_NAME" "$CI_REGISTRY_IMAGE:latest"
#    #     docker push "$CI_REGISTRY_IMAGE:latest"
#    #   fi
#  # Run this job in a branch where a Dockerfile exists
#  rules:
#    - if: $CI_COMMIT_BRANCH
#      exists:
#        - Dockerfile

deploy:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config get-contexts
    - kubectl config use-context lucasoskorep/personal-website:rpi-cluster
    - kubectl get pods -n website
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
      when: always
#deploy:
#  variables:
#    APP_NAME: chaosdev
#  stage: deploy
#  image:
#    name: alpine/helm:3.2.1
#    entrypoint:
#      - ""
#
#  script:
#    - ls
#    - helm upgrade ${APP_NAME} ./charts --install --values=./charts/values.yaml --namespace ${APP_NAME}
